/** Mirrors `INDUSTRY_TYPES` in EasyDukan_backend/constants/organisation.constant.ts */
export const INDUSTRY_TYPES = [
  "KIRANA_GENERAL_STORE",
  "GROCERY_SUPERMARKET",
  "MOBILE_ACCESSORIES",
  "ELECTRONICS_APPLIANCES",
  "COMPUTER_IT",
  "GARMENTS_TEXTILES",
  "FOOTWEAR",
  "JEWELLERY",
  "WATCHES_CLOCKS",
  "OPTICAL_EYEWEAR",
  "PHARMACY_MEDICAL",
  "AYURVEDIC_HOMEO",
  "COSMETICS_BEAUTY",
  "STATIONERY_BOOKS",
  "HARDWARE_TOOLS",
  "PAINT_BUILDING_MATERIAL",
  "PLYWOOD_TIMBER",
  "SANITARY_PLUMBING",
  "ELECTRICAL_SUPPLIES",
  "AUTOMOBILE_PARTS",
  "TWO_WHEELER_DEALER",
  "TYRES_TUBES",
  "LUBRICANTS_OIL",
  "RESTAURANT_CAFE",
  "BAKERY_CONFECTIONERY",
  "SWEETS_NAMKEEN",
  "DAIRY_MILK",
  "MEAT_FISH",
  "FRUITS_VEGETABLES",
  "GRAIN_PULSES",
  "SPICES_MASALA",
  "TEA_COFFEE",
  "BEVERAGES_COLD_DRINKS",
  "TOYS_GAMES",
  "GIFTS_FANCY",
  "HOME_DECOR",
  "FURNITURE",
  "KITCHENWARE_UTENSILS",
  "PLASTICS_HOUSEHOLD",
  "AGRO_INPUTS_SEEDS",
  "FERTILIZER_PESTICIDE",
  "DAIRY_EQUIPMENT",
  "PRINTING_XEROX",
  "LAUNDRY_DRY_CLEAN",
  "SALON_SPA",
  "GYM_FITNESS",
  "PET_SUPPLIES",
  "SPORTS_FITNESS_GOODS",
  "MUSICAL_INSTRUMENTS",
  "WHOLESALE_DISTRIBUTION",
  "IT_SERVICES",
  "SOFTWARE_DEVELOPMENT",
  "SOFTWARE_CONSULTANCY",
  "CONSULTANCY_SERVICES",
  "PROFESSIONAL_SERVICES",
  "ACCOUNTING_CA_SERVICES",
  "LEGAL_SERVICES",
  "ARCHITECTURE_ENGINEERING",
  "MARKETING_ADVERTISING",
  "DIGITAL_MARKETING",
  "WEB_DESIGN_DEVELOPMENT",
  "CLOUD_SAAS_SERVICES",
  "TELECOM_SERVICES",
  "COURIER_LOGISTICS",
  "TRANSPORT_TRAVEL",
  "EDUCATION_COACHING",
  "HEALTHCARE_SERVICES",
  "REPAIR_MAINTENANCE",
  "SECURITY_SERVICES",
  "EVENT_MANAGEMENT",
  "OTHER",
] as const;

export type IndustryType = (typeof INDUSTRY_TYPES)[number];

const INDUSTRY_LABEL_OVERRIDES: Partial<Record<IndustryType, string>> = {
  KIRANA_GENERAL_STORE: "Kirana / General store",
  GROCERY_SUPERMARKET: "Grocery / Supermarket",
  MOBILE_ACCESSORIES: "Mobile and accessories",
  ELECTRONICS_APPLIANCES: "Electronics and appliances",
  COMPUTER_IT: "Computer and IT",
  GARMENTS_TEXTILES: "Garments and textiles",
  PHARMACY_MEDICAL: "Pharmacy / Medical",
  AYURVEDIC_HOMEO: "Ayurvedic / Homeopathy",
  COSMETICS_BEAUTY: "Cosmetics and beauty",
  STATIONERY_BOOKS: "Stationery and books",
  HARDWARE_TOOLS: "Hardware and tools",
  PAINT_BUILDING_MATERIAL: "Paint and building material",
  PLYWOOD_TIMBER: "Plywood and timber",
  SANITARY_PLUMBING: "Sanitary and plumbing",
  ELECTRICAL_SUPPLIES: "Electrical supplies",
  AUTOMOBILE_PARTS: "Automobile parts",
  TWO_WHEELER_DEALER: "Two wheeler dealer",
  TYRES_TUBES: "Tyres and tubes",
  LUBRICANTS_OIL: "Lubricants and oil",
  RESTAURANT_CAFE: "Restaurant / Cafe",
  BAKERY_CONFECTIONERY: "Bakery and confectionery",
  SWEETS_NAMKEEN: "Sweets and namkeen",
  DAIRY_MILK: "Dairy and milk",
  MEAT_FISH: "Meat and fish",
  FRUITS_VEGETABLES: "Fruits and vegetables",
  GRAIN_PULSES: "Grain and pulses",
  SPICES_MASALA: "Spices and masala",
  TEA_COFFEE: "Tea and coffee",
  BEVERAGES_COLD_DRINKS: "Beverages and cold drinks",
  TOYS_GAMES: "Toys and games",
  GIFTS_FANCY: "Gifts and fancy",
  HOME_DECOR: "Home decor",
  KITCHENWARE_UTENSILS: "Kitchenware and utensils",
  PLASTICS_HOUSEHOLD: "Plastics and household",
  AGRO_INPUTS_SEEDS: "Agro inputs and seeds",
  FERTILIZER_PESTICIDE: "Fertilizer and pesticide",
  DAIRY_EQUIPMENT: "Dairy equipment",
  PRINTING_XEROX: "Printing / Xerox",
  LAUNDRY_DRY_CLEAN: "Laundry / Dry clean",
  SALON_SPA: "Salon / Spa",
  GYM_FITNESS: "Gym and fitness",
  PET_SUPPLIES: "Pet supplies",
  SPORTS_FITNESS_GOODS: "Sports and fitness goods",
  MUSICAL_INSTRUMENTS: "Musical instruments",
  WHOLESALE_DISTRIBUTION: "Wholesale distribution",
  IT_SERVICES: "IT services",
  SOFTWARE_DEVELOPMENT: "Software development",
  SOFTWARE_CONSULTANCY: "Software consultancy",
  CONSULTANCY_SERVICES: "Consultancy services",
  PROFESSIONAL_SERVICES: "Professional services",
  ACCOUNTING_CA_SERVICES: "Accounting / CA services",
  LEGAL_SERVICES: "Legal services",
  ARCHITECTURE_ENGINEERING: "Architecture and engineering",
  MARKETING_ADVERTISING: "Marketing and advertising",
  DIGITAL_MARKETING: "Digital marketing",
  WEB_DESIGN_DEVELOPMENT: "Web design and development",
  CLOUD_SAAS_SERVICES: "Cloud / SaaS services",
  TELECOM_SERVICES: "Telecom services",
  COURIER_LOGISTICS: "Courier and logistics",
  TRANSPORT_TRAVEL: "Transport and travel",
  EDUCATION_COACHING: "Education and coaching",
  HEALTHCARE_SERVICES: "Healthcare services",
  REPAIR_MAINTENANCE: "Repair and maintenance",
  SECURITY_SERVICES: "Security services",
  EVENT_MANAGEMENT: "Event management",
  OTHER: "Other",
};

export function formatIndustryTypeLabel(type: IndustryType): string {
  return (
    INDUSTRY_LABEL_OVERRIDES[type] ??
    type
      .toLowerCase()
      .split("_")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ")
  );
}

export const INDUSTRY_TYPE_OPTIONS = INDUSTRY_TYPES.map((type) => ({
  value: type,
  label: formatIndustryTypeLabel(type),
})).sort((a, b) => a.label.localeCompare(b.label));
