/** Shared SEO keyword pools for marketing landing pages (100+ per page). */

const BRAND = [
  "Mahajaan",
  "Mahajaan ERP",
  "Mahajaan billing software",
  "Mahajaan retail app",
  "Mahajaan POS",
  "Mahajaan GST software",
  "Mahajaan inventory software",
  "Mahajaan AI",
  "Mahajaan chatbot",
  "Mahajaan shop management",
  "mahajaan.com",
  "mahajaan.in",
  "Mahajaan India",
  "Mahajaan kirana app",
  "Mahajaan wholesale software",
];

const COMPETITORS = [
  "Vyapar",
  "Vyapar app",
  "myBillBook",
  "My Bill Book",
  "Tally",
  "TallyPrime",
  "Tally ERP 9",
  "Marg ERP",
  "Marg Billing",
  "Busy Accounting",
  "Busy ERP",
  "Khatabook",
  "Khata Book",
  "GoFrugal",
  "Gofrugal POS",
  "Zoho Books",
  "Zoho Invoice",
  "Swipe billing",
  "Swipe invoice",
  "Reach Accountant",
  "Refrens",
  "CaptainBiz",
  "ClearTax",
  "Hitech BillSoft",
  "ERPNext",
  "Odoo ERP",
  "BharatBills",
  "BillClap",
  "OkCredit",
  "Cashbook",
  "Just Billing",
  "Horizon ERP",
  "Miracle Accounting",
  "Saral Accounts",
  "ProfitBooks",
  "HostBooks",
  "Realbooks",
  "Giddh",
  "QuickBooks India",
  "Xero India",
  "Petpooja",
  "Bikayi",
  "Dukaan app",
  "Invoice Temple",
  "LOGIC ERP",
  "LOGIC retail",
  "RetailGraph",
  "eRetail Cybertech",
  "Ginesys",
  "Primaseller",
  "Unicommerce",
  "EasyEcom",
];

function competitorAlternatives(): string[] {
  const verbs = ["alternative", "alternative India", "vs", "replacement", "competitor", "free alternative"];
  const out: string[] = [];
  for (const name of COMPETITORS) {
    for (const v of verbs) {
      out.push(`${name} ${v}`);
      out.push(`Mahajaan ${v} ${name}`);
      out.push(`better than ${name}`);
    }
  }
  return out;
}

const CORE_RETAIL = [
  "retail ERP India",
  "retail ERP software",
  "retail billing software India",
  "shop billing software",
  "kirana billing app",
  "kirana shop software",
  "kirana store management",
  "GST billing software India",
  "GST invoice software",
  "GST billing app",
  "GST compliant billing",
  "CGST SGST billing",
  "IGST invoice software",
  "HSN code billing",
  "e-invoice software India",
  "e-way bill software",
  "POS billing India",
  "POS software for retail",
  "point of sale India",
  "counter billing software",
  "inventory management software",
  "stock management app",
  "low stock alerts",
  "party ledger software",
  "udhar khata software",
  "customer outstanding tracking",
  "purchase order software",
  "supplier management retail",
  "wholesale billing software",
  "distributor billing ERP",
  "pharmacy billing software",
  "medical store billing",
  "electronics shop billing",
  "mobile shop billing software",
  "hardware store software",
  "textile billing software",
  "FMCG distribution software",
  "retail accounting software",
  "small business ERP India",
  "SME billing software",
  "MSME retail software",
  "shop owner app",
  "dukan management software",
  "billing software Hindi",
  "Hindi billing app",
  "offline billing software",
  "cloud retail ERP",
  "web based billing software",
  "multi counter billing",
  "barcode billing software",
  "thermal printer billing",
  "GST report software",
  "GSTR-1 software",
  "profit and loss retail",
  "balance sheet for shop",
  "CA ready reports retail",
  "staff payroll retail shop",
  "employee salary software shop",
  "retail management system",
  "inventory and billing software",
  "all in one shop software",
  "Indian retail software",
  "best billing software India",
  "free billing software India",
  "affordable ERP India",
  "shop management app Android",
  "retail software 2026",
];

const AI_CHAT = [
  "AI billing assistant",
  "AI shop assistant India",
  "chatbot for shop owners",
  "WhatsApp billing bot",
  "manage shop by chat",
  "Hindi English shop AI",
  "voice billing retail",
  "AI inventory assistant",
  "smart product search retail",
  "semantic search inventory",
  "AI GST assistant",
  "retail chatbot India",
  "conversational ERP",
  "AI khata assistant",
  "daily sales summary chat",
];

const FEATURES = [
  "GST invoice generator",
  "sales invoice software",
  "purchase bill software",
  "serial number tracking",
  "IMEI tracking billing",
  "batch expiry tracking",
  "multi unit inventory",
  "stock valuation report",
  "party wise ledger",
  "payment reminder software",
  "credit limit tracking",
  "expense tracking shop",
  "cash flow retail",
  "day book report",
  "sales register GST",
  "purchase register",
  "stock summary report",
  "item wise profit report",
  "fast moving slow moving",
  "dead stock report",
  "payroll generation retail",
  "salary slip shop staff",
  "role based access shop",
  "multi user billing",
  "audit trail retail",
  "data export Excel",
  "Tally export billing",
  "PDF invoice WhatsApp",
  "print GST invoice",
  "custom invoice format",
];

const USE_CASES = [
  "kirana store ERP",
  "general store billing",
  "provision store software",
  "supermarket billing India",
  "mini supermarket POS",
  "mobile accessories shop",
  "electronics showroom software",
  "computer shop billing",
  "pharmacy inventory batch",
  "chemist shop GST",
  "hardware tools billing",
  "building material billing",
  "sanitary ware shop software",
  "garment shop billing",
  "textile showroom ERP",
  "fabric store inventory",
  "wholesale kirana software",
  "FMCG wholesaler billing",
  "distributor ERP India",
  "dealer management software",
  "contractor credit billing",
  "B2B retail billing",
  "retail chain software",
  "multi location shop billing",
  "franchise store billing",
];

const PRICING = [
  "free retail ERP trial",
  "billing software pricing India",
  "affordable shop software",
  "cheap GST billing app",
  "startup shop billing free",
  "early access billing software",
  "no credit card billing app",
  "monthly billing software plan",
  "yearly billing software India",
  "Vyapar pricing comparison",
  "myBillBook pricing comparison",
  "Tally pricing alternative",
  "free vs paid billing software",
  "SMB software pricing India",
  "growth plan retail ERP",
  "business plan shop software",
  "payroll add on billing",
  "unlimited invoices software",
  "multi staff plan retail",
];

const CONTACT = [
  "book demo retail software",
  "Mahajaan demo request",
  "billing software sales India",
  "ERP onboarding support",
  "shop software customer support",
  "retail software enquiry",
  "GST software contact",
  "Mahajaan support email",
  "schedule product demo shop",
  "retail ERP consultation",
  "migrate from Vyapar help",
  "migrate from myBillBook",
  "Tally migration support",
  "data import shop software",
  "implementation help retail",
];

const FAQ = [
  "billing software FAQ",
  "GST billing questions",
  "is Mahajaan safe",
  "retail ERP data security",
  "delete account billing app",
  "GST registration required billing",
  "offline mode billing app",
  "multi device login shop",
  "CA export GST reports",
  "how to use retail ERP",
  "inventory tracking help",
  "POS setup guide India",
  "staff access billing app",
  "pricing FAQ retail software",
  "free trial billing India",
];

const BLOG = [
  "retail operations blog",
  "GST guide shop owners",
  "kirana inventory tips",
  "POS best practices India",
  "retail payroll guide",
  "shop management articles",
  "Indian retail news",
  "billing mistakes avoid GST",
  "stock control tips kirana",
  "retail technology India",
  "small business finance shop",
  "udhar management tips",
];

function unique(...groups: string[][]): string[] {
  return [...new Set(groups.flat())];
}

const SHARED = unique(BRAND, COMPETITORS, competitorAlternatives(), CORE_RETAIL);

export const HOME_KEYWORDS = unique(SHARED, AI_CHAT, [
  "manage shop by chat",
  "WhatsApp shop assistant",
  "AI retail ERP India",
  "smart kirana software",
  "modern Vyapar alternative",
  "modern myBillBook alternative",
  "Tally alternative for shops",
  "Marg ERP alternative cloud",
  "Busy alternative retail",
  "Khatabook alternative full ERP",
  "GoFrugal alternative SMB",
  "Zoho Books alternative retail",
  "best shop ERP 2026",
  "retail AI assistant Hindi",
]);

export const FEATURES_KEYWORDS = unique(SHARED, FEATURES, AI_CHAT, [
  "Mahajaan features list",
  "full module retail ERP",
  "GST POS inventory payroll",
  "Vyapar features comparison",
  "myBillBook features comparison",
  "Tally features for retail",
  "Marg ERP modules comparison",
  "Busy features vs Mahajaan",
  "inventory serial tracking India",
  "retail ERP module list",
]);

export const USE_CASES_KEYWORDS = unique(SHARED, USE_CASES, [
  "retail use cases India",
  "sector wise billing software",
  "kirana vs electronics software",
  "pharmacy vs wholesale ERP",
  "Vyapar for kirana",
  "myBillBook for pharmacy",
  "Marg for distribution",
  "shop type billing solution",
]);

export const PRICING_KEYWORDS = unique(SHARED, PRICING, [
  "Mahajaan pricing plans",
  "compare Vyapar myBillBook price",
  "cheaper than Tally retail",
  "free tier billing software",
  "retail software cost India",
]);

export const CONTACT_KEYWORDS = unique(SHARED, CONTACT, [
  "contact Mahajaan team",
  "hello@mahajaan.com",
  "retail software demo India",
]);

export const FAQ_KEYWORDS = unique(SHARED, FAQ, [
  "Mahajaan frequently asked questions",
  "retail ERP help center",
  "billing app support India",
]);

export const BLOG_KEYWORDS = unique(SHARED, BLOG, [
  "Mahajaan blog retail India",
  "GST inventory POS articles",
]);

const BLOG_SLUG_KEYWORDS: Record<string, string[]> = {
  "gst-billing-guide-for-retail-shops": unique(BLOG_KEYWORDS, [
    "GST billing guide retail",
    "CGST SGST IGST explained",
    "HSN code for shop",
    "GST invoice format India",
    "GST mistakes small shop",
    "Vyapar GST billing",
    "myBillBook GST invoice",
    "Tally GST retail",
    "GSTR filing shop owner",
    "tax invoice requirements India",
    "composition scheme retail",
    "GST rate finder shop",
    "reverse charge retail",
    "B2B B2C GST billing",
    "GST bill format PDF",
  ]),
  "inventory-management-for-kirana-stores": unique(BLOG_KEYWORDS, [
    "kirana inventory management",
    "reduce dead stock kirana",
    "low stock alert kirana",
    "FMCG stock rotation",
    "Vyapar inventory",
    "myBillBook stock tracking",
    "Marg inventory retail",
    "shelf management kirana",
    "reorder level kirana",
    "stock taking kirana store",
    "SKU management kirana",
    "expiry tracking kirana",
    "warehouse kirana shop",
    "purchase planning retail",
    "stock valuation kirana",
  ]),
  "pos-billing-for-busy-counters": unique(BLOG_KEYWORDS, [
    "POS busy counter India",
    "fast billing retail counter",
    "barcode POS kirana",
    "thermal printer POS setup",
    "Vyapar POS counter",
    "myBillBook POS speed",
    "GoFrugal POS retail",
    "billing queue retail shop",
    "cashier software India",
    "touch POS billing",
    "keyboard shortcut billing",
    "multi item quick bill",
    "hold bill POS retail",
    "return exchange POS",
    "peak hour billing shop",
  ]),
  "staff-payroll-for-retail-shops": unique(BLOG_KEYWORDS, [
    "retail staff payroll India",
    "shop employee salary software",
    "attendance payroll retail",
    "salary slip shop staff",
    "payroll compliance small shop",
    "Vyapar payroll",
    "Tally payroll retail",
    "Busy payroll trading",
    "shop helper salary record",
    "overtime retail staff",
    "PF ESI small shop",
    "payroll Excel vs software",
    "monthly salary shop",
    "staff advance deduction",
    "payroll report CA retail",
  ]),
};

export function getBlogPostKeywords(slug: string): string[] {
  return BLOG_SLUG_KEYWORDS[slug] ?? unique(BLOG_KEYWORDS, [slug.replace(/-/g, " "), "Mahajaan blog article"]);
}

/** Ensures at least 100 keywords — pads with CORE if a page set is short. */
export function ensureMinKeywords(keywords: string[], min = 100): string[] {
  const set = unique(keywords, CORE_RETAIL, COMPETITORS);
  if (set.length >= min) return set;
  return unique(set, competitorAlternatives(), FEATURES, USE_CASES);
}
